name: Update index.html with new pages

on:
  push:
    paths:
      - '**/*.html'  # هر بار که فایل HTML جدید اضافه می‌شود

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get list of HTML files
        run: |
          echo "Fetching list of HTML files..."
          ls *.html > filelist.txt  # لیست فایل‌های HTML در پوشه جاری
          
      - name: Update index.html
        run: |
          # این بخش لیست صفحات جدید را در `index.html` اضافه می‌کند
          for file in $(cat filelist.txt); do
            if [[ "$file" != "index.html" ]]; then
              echo "<li><a href=\"$file\">$file</a></li>" >> index.html
            fi
          done
          
      - name: Commit updated index.html
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Update index.html with new pages"
          git push
